### ISSUE TITLE
Task wording vs. solution mismatch in exercise:dataset-equals-named-graph?

### ISSUE THREAD

**Issue by svatek** [jindrichmynarz/sparqlab#2]
The wording can be read as "IRI of any dataset ... with IRI of ANY graph in the store"
("zdali se IRI některých datasetů (instancí qb:DataSet) překrývají s IRI pojmenovaných grafů")
However, 
ASK
WHERE {GRAPH ?r {[] ?p [].}
  {?r a qb:Dataset }
          }
is labeled as incorrect, and the proposed solution presumes that the dataset IRI must collide with the IRI of THE graph where it occurs.
Did I miss something? Or should it be changed to "... s IRI jejich pojmenovaných grafů"?

**Comment by jindrichmynarz** [comment]
You're right. The wording of this exercise is not as precise as it could be. It was meant to ask for instances of `qb:DataSet` **in** the named graphs sharing the same IRI. As you point out, your query has a different meaning, so it's evaluated as incorrect. I'll fix this by rephrasing the exercise's description.
