### ISSUE TITLE
Nemožnost spustit/odeslat dotaz 

### ISSUE THREAD

**Issue by tomiaro** [jindrichmynarz/sparqlab#6]
Dobrý den,

po vyzkoušení několika cvičení na portále SPARQLab, které proběhly bez problémů,  funguje v současnosti aplikace chybně. Děje se tomu vždy nezávisle na vybraném cvičení. V případě spuštění dotazu nastává nekonečný loading a v případě odeslání výsledku server vrací error 500.

Děkuji

**Comment by jindrichmynarz** [comment]
Šlo o dočasný výpadek na serveru, který vyřešili kolegové z KIZI VŠE.
